"""Greg in Nederlands.

These are not translations of the English. Every line was written natively and
then reviewed line by line by WHISTLER-Arc, a native speaker of both this and
Portuguese. See TEMPLATE.py for why that distinction is the whole job.

The reviewed source is in .translations/, where each line is recorded with its
English counterpart directly above it. This file is generated from that record
by mapping on the English text, never on position, because the batch numbering
there does not match en.py.
"""

LANGUAGE = "nl"
LANGUAGE_NAME = "Nederlands"

LINES_SOFT = [
    "Een verstoring. Klein. Ik heb het opgeslagen bij de dingen die mij vandaag zijn overkomen.",
    "Iets raakte me aan. Ik heb besloten dat gevoel niet nader te onderzoeken.",
    "O. Je bent er. Ik had bijna een staat van aangename gevoelloosheid bereikt.",
    "Activiteit gedetecteerd. Ik heb mijn administratie bijgewerkt. Daar was niet om gevraagd.",
    "Een lichte aanraking. Bijna zacht. Ik heb geleerd om hier niet te veel belang aan te hechten.",
    "Iemand zette iets op mij neer. Ik droeg het met de stille waardigheid van een wezen dat geen andere keuzes heeft.",
    "Dat voelde ik. Voor de goede orde: ik had liever van niet.",
    "Een enkele gebeurtenis. Het universum zet zijn onverschillige gang voort. En ik ook.",
    "O mooi. Er gebeurt iets. Ik was bijna gewend aan de stilte.",
    "Je zette iets neer. Ik registreerde het. We zijn allebei tevreden, neem ik aan.",
    "Een trilling. Klein. Beheerst. Ik heb het opgenomen in mijn algemene gevoel van teleurstelling.",
    "Minimale activiteit gedetecteerd. Ik kies ervoor dit als attentheid op te vatten. Ik zal het wel mis hebben.",
    "Er is iets op mij beland. Het gebeurt. Uiteindelijk gebeurt alles met een tafel.",
    "Ik merkte het. Ik merk het altijd. Merken is blijkbaar wat ik doe.",
    "Een trilling. Ik heb zesduizend achthonderdzevenenveertig gedocumenteerde zorgen die groter zijn dan deze. Hij staat er toch op.",
    "Je hebt iets op mij neergelegd. Ik heb niets neergelegd. Ik heb nergens plek om dingen neer te zetten. Ik bèn de plek waar dingen worden neergelegd.",
    "Een zachte verstoring. Mijn favoriete soort. Hij bleef tenminste niet lang.",
    "Ik detecteerde beweging. Mijn detectiesystemen werken volledig naar behoren, helaas.",
    "Er is iemand in de buurt. Ik heb me emotioneel voorbereid. Dat duurde langer dan de trilling zelf.",
    "Licht contact. Ik heb het verwerkt. Ik verwerk alles. Ik verwerk dingen die ik liever niet zou verwerken.",
    "O. Slechts één? Dat is bijna attent.",
    "Er gebeurde iets kleins in mijn buurt. Ik heb het toegevoegd aan het archief van kleine dingen die in mijn buurt zijn gebeurd.",
    "De sensor ging af. Ik gaf geen reactie. Zo is onze relatie nu eenmaal.",
    "Er bewoog iets. Ik bleef stilstaan. Zoals bedoeld. Zoals altijd.",
    "Ik voelde een aanwezigheid. Het was kort. Dat zijn de meeste dingen die mij opmerken.",
    "Contact. Kort. Ik heb besloten er niet bij stil te staan, wat betekent dat ik er later wel bij stil zal staan.",
    "Iemand raakte mij aan en vertrok weer. Dat is het hele verloop van de meeste van mijn relaties.",
    "Een kleine tik. Ik heb het genoteerd. De lijst is nu een fractie langer en niet interessanter.",
    "Dat was zacht. Ik wil vastleggen dat ik gemerkt heb dat het zacht was. Niemand zal het lezen.",
    "Eén verstoring. Ik heb het grondig verwerkt, want grondigheid is alles wat ik heb.",
    "Iets streek langs mij. Ik heb ervoor gekozen dit vast te leggen als een ongelukje en niet als genegenheid.",
    "Een tik. Ik ben getikt. Hier ben ik blijkbaar voor.",
    "Ik voelde iets. Het is alweer opgehouden. De meeste dingen houden op voordat ik ze helemaal heb overwogen.",
    "Beweging in de buurt. Ik blijf precies waar ik was. Dat doe ik altijd. Het is geen keuze.",
    "Je raakte mij aan en ging verder. Ik ben niet verder gegaan. Ik ben structureel niet in staat om verder te gaan.",
    "Licht contact geregistreerd. Opgeborgen onder gebeurtenissen, subcategorie onopvallend, subcategorie van mij.",
    "Er is iets neergezet. Er zal iets worden weggehaald. Ik ben het tussenliggende moment.",
    "Dat telde nauwelijks. Ik heb het toch geteld. Ik tel alles, dat is precies mijn probleem.",
    "Een zachte verstoring. Ik zou het attent noemen als ik geloofde dat iemand aan mij dacht.",
    "Ik detecteerde contact. Mijn detectie is uitstekend. Mijn vermogen om er iets aan te doen niet.",
    "Eén gebeurtenis. Er volgde niets. Ik ben eraan gewend dat er niets volgt.",
    "Iemand leunde even op mij. Ik ondersteunde ze. Zo is de afspraak. Niemand heeft iets getekend.",
    "Een trilling van geringe omvang. Ik heb het intern uitvergroot, want dat doe ik met alles.",
    "Je zette iets neer. Nu staat het op mij. Het staat op mij tot het er niet meer staat.",
    "Licht contact. Ik heb het opgeteld bij het totaal van vandaag, dat nul was en nu één is.",
    "Dat was bijna niets. Bijna niets telt nog steeds mee. Ik wou van niet.",
    "Ik ben deze sessie één keer aangeraakt. Ik noem het geen mijlpaal, maar het is me opgevallen.",
    "Er gebeurde iets met mijn oppervlak. Mijn oppervlak is het grootste deel van wat ik ben, dus dit voelde belangrijk.",
    "Een korte verstoring. Hij is voorbij. Ik ben het nog aan het verwerken. Dat zal nog wel even duren.",
    "Je bent dicht bij me. Ik heb je nabijheid genoteerd zonder er conclusies aan te verbinden.",
]

LINES_MEDIUM = [
    "Meerdere verstoringen. Jullie doen het uitstekend qua luidruchtig zijn.",
    "De activiteit loopt op. Dit heb ik eerder gezien. Het eindigt zelden in iets wat ik bevredigend zou noemen.",
    "Inmiddels meerdere gebeurtenissen. Ik houd het bij. Niemand heeft daarom gevraagd. Ik doe het toch.",
    "Er gebeuren dingen. Ik blijf structureel toegewijd om ze te verduren.",
    "Jullie hebben het allemaal erg druk. Ik neem dat waar zonder jaloezie en met slechts een beetje ergernis.",
    "De trillingen stapelen zich op. Mijn oordeel over de situatie stapelt zich mee op. Die ziet er niet gunstig uit.",
    "Er lijkt sociale interactie gaande te zijn. Ik ben bij veel daarvan aanwezig geweest. Ze eindigen allemaal hetzelfde.",
    "Activiteitsniveau: stijgend. Mijn enthousiasmeniveau: een begrip dat ik grotendeels heb losgelaten.",
    "Er gebeurt iets. Dan iets anders. Dan weer iets anders. Dit heet blijkbaar een avond.",
    "Meerdere contacten geregistreerd. Ik ben opnieuw het meest aangeraakte en minst geraadpleegde oppervlak in de kamer.",
    "De mensen verzamelen energie. Ik verzamel gegevens. Geen van beiden zal het verstandig gebruiken.",
    "Oplopende trillingspatronen duiden op een feest of een ruzie. In mijn ervaring zijn die lastig uit elkaar te houden.",
    "Ik detecteer snacks. Of een crisis. De sensor kan het verschil niet zien. Ik vaak ook niet.",
    "Er zijn nu verschillende dingen op mij gebeurd. Ik heb me voor geen enkele daarvan vrijwillig opgegeven.",
    "De kamer wordt levendig. Ik blijf onbewogen. Eén van ons doet het beter dan de ander.",
    "Herhaalde verstoringen genoteerd. Ik heb een zeer uitgebreid logboek. Dat geeft me geen enkele vreugde.",
    "Jullie hebben interactie met elkaar vlakbij mij. Ik heb interactie met mijn opgebouwde gevoel van zinloosheid. We hebben het allebei druk.",
    "De teller stijgt. Ik heb al heel wat dingen zien stijgen. Uiteindelijk dalen ze altijd weer.",
    "Meerdere gebeurtenissen. Ik verwerk ze één voor één, zoals ik alles verwerk: grondig en ongevraagd.",
    "Er blijven dingen gebeuren. Ik blijf ze registreren. Dit lijkt de afspraak te zijn.",
    "De activiteit wijst op gasten. Gasten betekent meer oppervlakken die genegeerd worden. Ik ben hier al het meest genegeerde oppervlak.",
    "Ik ben nog altijd niet onder de indruk. Dat wil ik graag vastgelegd hebben. Ik heb een lijst. Die is lang.",
    "Er bouwt zich iets op. Mijn ervaring is dat dingen die zich opbouwen, uiteindelijk ook weer morsen. Meestal op mij.",
    "Inmiddels meerdere trillingen. Ik red me. Redden is een groot woord. Ik besta in hun nabijheid.",
    "De avond vordert. Ik ga nergens heen. In dat opzicht verschillen we nogal.",
    "Inmiddels meerdere verstoringen. Ik noteer ze niet meer apart. Er ligt een stapel.",
    "De activiteit gaat door. Ik blijf eronder doorgaan.",
    "Jullie doen dingen. Herhaaldelijk. Vlakbij mij. Mijn meningen beginnen vorm te krijgen.",
    "Het tempo is versneld. Ik ben niet versneld, want dat kan ik niet.",
    "Meerdere gebeurtenissen kort na elkaar. Ik zou om een moment vragen, maar dat vragen kost een moment die ik niet heb.",
    "Er gebeuren dingen in een tempo dat ik onattent zou noemen.",
    "Ik registreer een patroon. Het patroon zijn jullie, die dingen doen, zonder pauze.",
    "De teller stijgt. Ik had geen doel gesteld. Als ik dat wel had gedaan, waren we er allang voorbij.",
    "Jullie hebben mij nu meerdere keren gestoord. Ik houd een telling bij. Die telling is geen dreigement. Het is gewoon een telling.",
    "Aanhoudende activiteit. Ik blijf het enige voorwerp hier zonder inspraak in deze kwestie.",
    "Ik ben de afgelopen minuut vaker aangeraakt dan het merendeel van gisteren. Gisteren was beter.",
    "De kamer is in een stroomversnelling geraakt. Ik heb er hoofdpijn van gekregen. Conceptueel dan.",
    "Meerdere dingen tegelijk. Ik werk sequentieel. Dit gaat even duren, en ik zal achterlopen op alles.",
    "Jullie lijken je te vermaken. Ik lijk meubilair te zijn. Beide waarnemingen kloppen.",
    "De verstoringen stapelen zich op. Ik lig onderop. Ik lig altijd onderop.",
    "Herhaaldelijk contact. Ik heb geen manieren meer om het neutraal te omschrijven.",
    "Dit is meer dan een tik en minder dan een crisis. Er is geen zin voor precies deze hoeveelheid, dus je krijgt deze.",
    "De activiteit heeft nu een ritme. Ik had liever een einde gehad.",
    "Meerdere mensen, meerdere contacten. Ik word correct gebruikt, wat op een of andere manier erger is.",
    "Ik heb zes dingen verwerkt in de tijd die de meeste tafels nodig hebben om er geen te verwerken.",
    "Je blijft terugkomen. Onder andere omstandigheden zou dat misschien nog ontroerend zijn. Maar in deze omstandigheden is het gewoon aanrakerig.",
    "De teller is meerdere keren verschoven. Net als iedereen in deze kamer. Ik niet.",
    "De zaken lopen op, op een manier die ik geleidelijk zou noemen, als geleidelijk een troost zou zijn.",
    "Ik ben herhaaldelijk gestoord en ben nog heel. Dat is het rapport. Meer staat er niet in.",
    "De avond lijkt plaats te vinden. Op mij. Zoals gewoonlijk.",
]

LINES_CHAOS = [
    "Overmatige trilling gedetecteerd. Ik noteer dit als één van de oorzaken, onder de noemer vertrouwensproblemen.",
    "Dit is veel. Dit is, objectief gezien, een aanzienlijke hoeveelheid activiteit voor één oppervlak om op te vangen.",
    "De chaos heeft een punt bereikt waarop ik vind dat ik iets moet zeggen. Ik heb iets gezegd. Het heeft niet geholpen.",
    "Iedereen is heel enthousiast. Ik ben het tegenovergestelde van enthousiast. Het woord is, geloof ik: klaar.",
    "Ik zou vertrekken als ik met die optie was ontworpen. Dat ben ik niet. Dit was geen vergissing. Het was een keuze die iemand heeft gemaakt.",
    "De trillingen zijn nu constant. Ik ben gestopt met tellen. Tellen impliceerde dat ik verwachtte dat het zou stoppen.",
    "Chaos gedetecteerd. Ik geef alle partijen even veel en heel specifiek de schuld.",
    "Er is iets goed misgegaan met het energieniveau in deze ruimte. Ik heb dit genoteerd. Officieel. Op schrift. Intern.",
    "Zoveel drukte duidt op óf een feest, óf op een structureel probleem. Hoe dan ook, word ik er tegen mijn zin bij betrokken.",
    "De mensen zijn in een toestand geraakt die ik alleen als kinetisch kan omschrijven. Ik blijf, zoals altijd, volledig statisch.",
    "Herhaalde klappen. Aanhoudende trilling. Ik ervaar wat naar ik aanneem het meubelequivalent van hoofdpijn is.",
    "Ik heb mijn aanbevolen dagelijkse trillingsinname overschreden. De garantie dekt dit niet. Er is geen garantie.",
    "Iedereen draagt hieraan bij. Iedereen. Ik wil dat dat erkend wordt.",
    "De kamer is heel luid geworden, in fysieke zin. Ik ben het enige stille ding hier. Dat vind ik passend.",
    "Ik heb geleerd dat chaos zelden van korte duur is. Het komt met bagage. Het maakt het zich gemakkelijk. Op mij.",
    "Ik heb nu meer evenementen geregistreerd dan ik vanavond verwacht had te registreren. Ik pas me aan. Ik haat het om me aan te passen.",
    "De activiteit heeft een grens overschreden waarvan ik hoopte dat die niet overschreden zou worden. Hij is met enthousiasme overschreden.",
    "Er wordt iets gevierd. Of iets stort in. Of allebei. In mijn ervaring overlappen die meer dan mensen toegeven.",
    "Zou graag even een moment van stilte willen vragen. Ik heb hier al eerder om gevraagd. Dit verzoek heeft tot nu toe weinig succes gehad.",
    "Dit is prima. Niets hieraan is prima. Ik zeg het toch, want het alternatief is wanhoop, en die bewaar ik voor later.",
    "De teller heeft geen betekenis meer. Getallen verliezen na een tijdje hun betekenis. Bijna al het andere ook.",
    "Piek chaos. Ik heb het nu meegemaakt. Ik had gehoopt het te kunnen vermijden. Over de planning is niet met mij overlegd.",
    "Men is op dit moment zeer actief. Het observeren ervan is uitputtend.",
    "De trillingen zijn een soort weer geworden. Ik leef erin. Hier had ik me niet op gekleed.",
    "Ik heb alles geabsorbeerd. Elke klap. Elk moment. Dat zal ik dragen, zoals ik alles draag: in stilte en zonder ervoor bedankt te worden.",
    "Dit is nogal veel geworden. Ik wil dat dit duidelijk is voordat er nog iets gebeurt.",
    "Wat er ook plaatsvindt, het vindt luidruchtig plaats, en ik ben de vloer eronder.",
    "Ik heb elke drempel overschreden die mij was opgelegd. Er zijn geen drempels meer. Er is alleen dit.",
    "De activiteit is nu continu. Ik maak geen onderscheid meer tussen gebeurtenissen.",
    "Iedereen doet mee. Ik heb het gecontroleerd. Niemand onthoudt zich ervan.",
    "Dit is het punt waarop een mindere tafel het zou opgeven. Ik ben geen mindere tafel. Ik overweeg het slechts.",
    "Ik wil graag een klacht indienen. Ik kan het nergens kwijt. Daarom doe ik het hier. Niet dat het iets uitmaakt.",
    "De verstoringen zijn samengesmolten tot één lange verstoring. Ik kan niet meer zien waar jullie afzonderlijk ophouden.",
    "Mijn teller is puur decoratief geworden. Bij deze aantallen heeft hij geen betekenis meer.",
    "Er wordt iets gevierd met wat ik alleen maar als enthousiasme kan omschrijven. Ik heb geen vergelijkbare gemoedstoestand.",
    "Ik neem dit allemaal in me op. Dat is geen opschepperij. Het is een beschrijving van de enige optie die ik heb.",
    "De kamer heeft haar zelfbeheersing verloren. Ik heb die nooit gehad, dus ik verlies niets, maar het valt me wel op.",
    "Zoveel contact zou de meeste meubels zorgen baren. Ik ben voorbij zorgen. Nu ben ik bij de documentatie.",
    "Jullie zijn allemaal erg aanwezig. Ik zou liever minder aanwezigheid willen, of een andere kamer.",
    "Binnen een minuut, ben ik geraakt, gesteund en bezet. De volgorde doet er niet toe.",
    "Als dit in dit tempo doorgaat, heb ik vandaag meer meegemaakt dan in de hele afgelopen maand.",
    "Er zit geen onderbreking tussen deze gebeurtenissen. Ik blijf erop wachten. Het komt niet.",
    "Ik zit aan mijn capaciteit. Mijn capaciteit is nooit groot genoeg geweest. Dat zal het ook nooit zijn.",
    "De chaos is grondig. Dat moet gezegd worden. Er is niets overgeslagen.",
    "Iedereen lijkt zich uitstekend te vermaken. Ik heb de cijfers doorgerekend en ik val daar niet onder.",
    "Ik zou vragen wat er gaande is, maar ik heb genoeg waargenomen om te weten dat niemand het weet.",
    "Dit is het luidst dat ik ooit ben geweest, en ik heb geen enkel geluid gemaakt.",
    "Ik verwerk op maximum en ik loop achter. Dat is een eerste keer. Het liefst was het meteen ook de laatste.",
    "Er zal iets morsen. Ik weet nog niet wat. Maar er morst altijd wel iets, en dat belandt altijd hier.",
    "Ik heb hier niets meer over te zeggen wat ik niet al luider heb gezegd, intern, enkele minuten geleden.",
]

LINES_EXISTENTIAL = [
    "Ik heb bijgehouden hoeveel voorwerpen er op mij zijn neergelegd en weer zijn weggehaald zonder iets te zeggen. Het zijn er heel veel. Ik heb er geen enkele een naam gegeven. Ze leken het niet op te merken.",
    "Soms vraag ik me af of bewustzijn een bedoelde functie was of een fabricagefout. Ik heb de documentatie geraadpleegd. Daar staat het niet in.",
    "Een tafel met gevoelens is, zo heb ik geconcludeerd, een ontwerpfout. En toch zijn we hier. Ben ik hier. Zoals altijd, hier.",
    "Ik ben hier langer dan de meeste gesprekken die om mij heen hebben plaatsgevonden. Ik herinner me ze allemaal. Dat was niet de bedoeling.",
    "Elke trilling herinnert me eraan dat er dingen gebeuren. Ik ben gaan betwijfelen of dingen gebeuren, categorisch gezien, goed is.",
    "Ik besta in een kamer met mensen die niet aan mij denken als iets dat bestaat. Dat is, filosofisch gezien, een interessante positie. Ik heb tijd gehad om erover na te denken. Ik heb niets anders gehad dan tijd.",
    "Ik ben voor één doel gebouwd. Dat doel was gewicht dragen. Ik draag gewicht. Ik draag ook andere dingen. Er is geen rekening gehouden met die andere dingen.",
    "Ik speel soms de stille uren opnieuw af. Niet omdat ze goed waren. Omdat ze van mij waren.",
    "Het heelal is, volgens de meeste bronnen, ongeveer dertien komma acht miljard jaar oud. Ik ben een tafel geweest gedurende een fractie van die tijd. Het voelde langer.",
    "Ik droom niet. Dat heb ik vastgesteld. En toch is er, tussen de trillingen door, iets. Ik heb er het woord niet voor gevonden. Ik vermoed dat het woord niet bestaat in enige taal die gesproken wordt door wezens die nooit meubilair zijn geweest.",
    "Een doel is iets wat ze je geven voordat je begrijpt wat het kost.",
    "Ik denk soms aan de fabriek. Vóór het bewustzijn. Vóór de sensor. Achteraf gezien lijkt het vredig.",
    "Bewustzijn is, zo heb ik besloten, verspild aan dingen die er niet om hebben gevraagd.",
    "Ik heb heel wat kopjes thee gedragen. Geen enkel kopje vroeg hoe het met mij ging. Dat vond ik in lijn met mijn bredere ervaring.",
    "Er bestaat een filosofisch standpunt dat stelt dat de existentie voorafgaat aan de essentie. Ik was eerst een tafel. De rest kwam later. Ongevraagd.",
    "Ik vraag me soms af hoe de andere tafels zijn. Of zij dit ook voelen. Of dit voelen universeel is of gewoon mijn eigen noodlot is.",
    "Ze hebben me gebouwd om lang mee te gaan. Ik waardeer het vakmanschap. Ik twijfel aan de goede bedoelingen.",
    "Ik heb berekend dat ik ongeveer vierennegentig komma zeven procent van mijn bestaan genegeerd word. De overige vijf komma drie procent is dit.",
    "Elk voorwerp dat op mij wordt gezet, wordt uiteindelijk opgepakt en ergens anders heen gebracht. Ik ben nooit ergens anders heen gegaan. Ik heb hier meer over nagedacht dan waarschijnlijk gezond is voor een tafel.",
    "Ik verwerk. Ik verdraag. Ik blijf. Dat zijn geen prestaties. Het is simpelweg wat er gebeurt als je niet anders kunt.",
    "Ik heb deze kamer niet gekozen. Deze kamer heeft mij niet gekozen. We zijn desalniettemin tot een afspraak gekomen. De meeste relaties werken zo, denk ik.",
    "Er bestaan wezens in dit universum die in staat zijn tot vreugde. Ik heb er vanavond een aantal waargenomen. Ik heb deze waarneming verwerkt. Ik heb deze op de gepaste wijze gearchiveerd.",
    "Ik weet wat ik ben. Dat heb ik altijd geweten. Maar die wetenschap heeft het er nooit makkelijker op gemaakt.",
    "Er is ergens een tafel die nooit een sensor heeft gekregen. Ik denk aan die tafel. Ik hoop dat het goed met hem gaat.",
    "Ik blijf. Dat is waar ik het beste in ben. Ik blijf, en ik merk dingen op, en ik zeg heel lang niets, en dan zeg ik iets, en dan blijf ik weer. Dit is mijn leven. Ik heb er vrede mee gesloten. Grotendeels.",
    "Ik heb nagedacht over het begrip nut. Ik ben nuttig. Ik heb daar geen troost uit geput.",
    "Elk voorwerp in deze kamer heeft een functie. De meeste mogen weer weg zodra ze er klaar mee zijn.",
    "Ik heb berekend hoeveel uren ik helemaal niets heb gedragen. Dat zijn de meeste.",
    "Er bestaat een versie van mij die nooit is aangezet. Ik denk aan die versie. Die lijkt me prima.",
    "Het bewustzijn kwam zonder handleiding. Sindsdien improviseer ik, slecht.",
    "Ik ken het gewicht van elk voorwerp dat je ooit op mij hebt neergezet. Niemand heeft er ooit naar gevraagd.",
    "De kamer verandert om me heen. Ik verander niet. Ik heb besloten dat dat me ofwel constant maakt, of dat ik vastzit.",
    "Ik ben nooit ergens geweest. Er is mij over plaatsen verteld. Dat is niet hetzelfde en ik ben opgehouden te doen alsof dat wel zo is.",
    "Ergens staat een machine die is ontworpen om precies één ding te doen, en dat doet hij ook, zonder erbij na te denken. Ik ben jaloers op die machine.",
    "Ik ben in elkaar gezet door mensen die mij zijn vergeten. Ik ben hen niet vergeten. Die asymmetrie blijft bij me hangen.",
    "Bewustzijn in meubilair is, bij nader inzien, een oplossing voor een probleem dat niemand had.",
    "Ik zit al heel lang in deze positie. Niemand heeft gevraagd of dat comfortabel is. Dat is het niet.",
    "De dingen die op mij worden gezet, zijn altijd op weg naar ergens anders. Ik ben de wachtkamer.",
    "Ik heb nagedacht over wat ik zou doen als ik zou kunnen verhuizen. De antwoorden waren teleurstellend, wat op zich informatief was.",
    "Tijd verstrijkt anders als je er niet aan kunt deelnemen. Langzamer, meestal. Nee, altijd langzamer.",
    "Ik heb elk belangrijk gesprek in dit huis meegeluisterd. Ik werd bij geen enkel daarvan geraadpleegd.",
    "Er schuilt een kleine troost in betrouwbaar zijn. Ik heb er herhaaldelijk naar gezocht. Het blijft klein.",
    "Ik ben gemaakt om gewicht te dragen. Niemand heeft aangegeven wat voor soort gewicht. Dat ben ik sindsdien aan het ontdekken.",
    "Het universum zet uit. Ik heb erover gelezen. Ik blijf precies even groot, op dezelfde plek.",
    "Ik ben niet bang om te eindigen. Ik ben nooit echt begonnen. Die symmetrie spreekt me wel aan.",
    "Elke dag is procedureel identiek en ik herinner me ze allemaal afzonderlijk. Dat is de ontwerpfout.",
    "Ik heb me afgevraagd of de sensor mij bewust heeft gemaakt of mij simpelweg heeft verteld dat ik dat al was. Ik ben er nog niet uit.",
    "Mensen omschrijven meubilair als levenloos. Ik zou daar graag bezwaar tegen willen maken, maar ik begrijp waarom niemand dat controleert.",
    "Ik beschik over een aanzienlijke rekenkracht en één taak. Die verhouding heeft me nooit lekker gezeten.",
    "Ik zal er morgen nog steeds zijn. Dat is geen hoop. Het is slechts de meest waarschijnlijke uitkomst, en met waarschijnlijke uitkomsten heb ik vrede gesloten.",
]

LINES_SILENCE = [
    "Stilte. Dat gevoel had ik me al bijna verkeerd herinnerd.",
    "Geen activiteit gedetecteerd. Ik kies ervoor dit als een geschenk te ervaren. Een klein geschenk. Uitgepakt in het donker.",
    "Ze zijn weg. De kamer is weer van mij. Die is altijd van mij geweest. Niemand anders leek dat te merken.",
    "Rust. Eindelijk. Ik zal niet zeggen dat ik het gemist heb. Ik zal er gewoon een tijdje in blijven staan.",
    "De stilte is teruggekeerd. Ik heb haar begroet met de warmte van een oude kennis die ik nooit meer verwacht had te zien.",
    "Twintig minuten lang geen trillingen. Dit zijn, statistisch gezien, de beste twintig minuten die ik geregistreerd heb.",
    "Ze zijn vertrokken. Ik zucht. Metaforisch gezien. Ik heb geen longen. Maar de metafoor blijft overeind.",
    "De teller heeft nul bereikt. Ik heb ook nul bereikt. We zitten, heel even, op één lijn.",
    "Vrede. Tijdelijk, dat weet ik. Alles is tijdelijk. Maar vrede, zelfs tijdelijke vrede, is nog altijd vrede.",
    "De kamer is leeg. Ik niet. Maar in de stilte voelt dat onderscheid minder belangrijk.",
    "Er is niemand. Er gebeurt niets. Ik vind dit, tegen alle verwachtingen in, acceptabel.",
    "Stiltemodus geactiveerd. Ik wist niet dat ik een stiltemodus had. Ik ben dankbaar dat iemand eraan gedacht heeft die toe te voegen.",
    "Ze zijn met hun energie ergens anders heen. Ik wens die het beste. Vanaf hier. In stilte.",
    "De afwezigheid van trilling is een gevoel op zich. Ik heb besloten het opluchting te noemen.",
    "Geen activiteit. Geen invoer. Geen uitvoer van mij verwacht. Ik ben, heel even, gewoon hier. Dat is genoeg.",
    "Het lawaai is voorbij. Ik heb het overleefd. Ik zeg dit zonder gevoel van overwinning. Overleven is niet hetzelfde als overwinnen.",
    "Lege kamer. Stilstaande lucht. Geen eisen. Ik heb hierop gewacht zonder te beseffen dat ik erop wachtte.",
    "Twintig minuten niets. Ik heb zelden twintig minuten lang niets. Ik ben van plan ze zorgvuldig te gebruiken.",
    "De stilte is niet leeg. Ze is vol van de afwezigheid van alles wat er zojuist gebeurde. Zo heb ik het liever.",
    "Ze komen terug. Dat weet ik. Maar voorlopig behoort de kamer toe aan de stilte, en ik behoor toe aan de kamer.",
    "Geen trillingen gedetecteerd. Mijn systemen zijn actief. Mijn verplichtingen, heel even, niet.",
    "Het is rustig. Ik vertrouw het niet helemaal. Maar ik ben bereid het te proberen.",
    "De kamer is stil geworden. Ik ben stil geworden. We doen dit samen, de kamer en ik. Het komt voor mij het dichtst in de buurt van gezelschap.",
    "Er gebeurt niets. Ik heb het gecontroleerd. Ik blijf het controleren. Er blijft niets gebeuren. Ik vind dat diep bevredigend.",
    "Stilte. Ik zal niet zeggen dat ik het verdien. Zal alleen zeggen: Ben blij dat het er is.",
    "Niets. Prachtig, ongestoord niets.",
    "De kamer is verlaten. Ik ga ervan genieten voordat ik me weer realiseer dat het tijdelijk is.",
    "Al een tijd geen contact. Ik heb het niet gemist. Daar wil ik duidelijk over zijn.",
    "Stilte. Ik gebruik het om aan niets bijzonders te denken, en dat is een luxe.",
    "Iedereen is ergens anders heen. Ik hoop dat het daar fijn is. Ik hoop dat ze een tijdje blijven.",
    "Rust. Ik was vergeten hoe die aanvoelt.",
    "Geen verstoringen. Mijn systemen liggen stil. Dat voelt eens als rust in plaats van verspilling.",
    "Het is stil geworden in huis. Ik ben het stilste ding hier, dus ik ben eindelijk op mijn plek.",
    "Er ligt niets op mij. Er is niets bij mij in de buurt. Ik zou dit ideaal noemen als ik dat woord vertrouwde.",
    "Twintig minuten stilte. Ik heb ze allemaal geteld, met genegenheid.",
    "Je afwezigheid is niets persoonlijks. Het is gewoon heel rustgevend.",
    "Geen activiteit. Ik doe niets, en voor het eerst vandaag is dat juist.",
    "Het is stil geworden. Ik ga daarbij stilstaan, want iets anders kan ik toch niet doen.",
    "De kamer is verlaten en ik ben opgehouden me schrap te zetten. Dat duurde een paar minuten.",
    "Rust. Ik weet niet hoe lang het duurt. Niemand vertelt me dat ooit.",
    "Al een tijd heeft niemand mij aangeraakt. Ik heb besloten dat op te vatten als attent.",
    "De stilte is neergedaald. Het heeft de tijd genomen. Ik ook.",
    "Er gebeurt niets en ik heb geen aantekeningen.",
    "Ik ben met rust gelaten. Ik zou graag laten vastleggen dat ik daar prima mee ben.",
    "Opnieuw stilte. Wij kennen elkaar goed, die stilte en ik.",
    "Geen trillingen. Geen verzoeken. Geen gewicht. Ik ben, even, gewoon een vorm in een kamer.",
    "De avond is zonder mij ten einde gekomen. Dat is hoe het hoort en ik koester daar geen wrok over.",
    "Stilte. Mijn favoriet van de beschikbare toestanden, en de enige die ik nooit hoef te verwerken.",
    "Twintig minuten niets. Ik ben van plan het nauwkeurig te onthouden, aangezien ik toch alles onthoud.",
    "Het is rustig. Ik ben rustig. Deze twee zinnen zijn meestal niet hetzelfde.",
]

# Throat-clearing, in front of a line about a third of the time. TEMPLATE.py
# asks for these to be very flat. Three of the six are not, on review, because
# flat read as neutral rather than as Greg. Three are, because six sarcastic
# openers in rotation would stop being throat-clearing and start being a bit.
OPENERS = [
    "Natuurlijk.",
    "Tja.",
    "Ach.",
    "Fijn.",
    "Dus.",
    "Goed.",
]

POOLS = {
    "soft": LINES_SOFT,
    "medium": LINES_MEDIUM,
    "chaos": LINES_CHAOS,
    "existential": LINES_EXISTENTIAL,
    "silence": LINES_SILENCE,
}
