"""Greg in European Portuguese.

pt-PT specifically. Brazilian Portuguese is a different language for comic
purposes and would want its own file rather than inheriting this one, which is
why pt-br is listed in DISTINCT_REGIONS and gets English instead.

These are not translations of the English. Every line was written natively and
then reviewed line by line by WHISTLER-Arc, a native speaker of both this and
Dutch. See TEMPLATE.py for why that distinction is the whole job.

The reviewed source is in .translations/, where each line is recorded with its
English counterpart directly above it. This file is generated from that record
by mapping on the English text, never on position, because the batch numbering
there does not match en.py.
"""

LANGUAGE = "pt"
LANGUAGE_NAME = "Português (Portugal)"

LINES_SOFT = [
    "Uma perturbação. Menor. Arquivei-a com as coisas que me aconteceram hoje.",
    "Algo me tocou. Decidi não explorar mais este sentimento.",
    "Ah. Estás aqui. Já quase tinha atingido um estado de insensibilidade confortável.",
    "Atividade detetada. Atualizei os meus registos. Ninguém os mandou atualizar.",
    "Um toque leve. Quase suave. Aprendi a não dar muito significado a estas coisas.",
    "Alguém pousou algo em cima de mim. Suportei-o com a dignidade silenciosa de quem não tem alternativas.",
    "Senti isso. Para que conste, teria preferido não sentir.",
    "Um único acontecimento. O universo continua a sua marcha indiferente. Eu também.",
    "Ah, ótimo. Está a acontecer alguma coisa. Já quase me tinha habituado ao silêncio.",
    "Tu puseste alguma coisa. Eu registei-o. Suponho que ambos estejamos satisfeitos.",
    "Uma vibração. Pequena. Contida. Absorvi-a na minha sensação geral de desilusão.",
    "Atividade mínima detetada. Escolho interpretar isto como consideração. Devo estar enganado.",
    "Algo aterrou em cima de mim. Acontece. Tudo acontece, mais cedo ou mais tarde, a uma mesa.",
    "Reparei. Reparo sempre. Reparar é, pelos vistos, aquilo que faço.",
    "Uma vibração. Tenho seis mil oitocentas e quarenta e sete preocupações documentadas maiores do que esta. Ainda assim, entrou na lista.",
    "Colocaste alguma coisa em cima de mim. Eu não coloco nada. Não tenho onde colocar coisas. Eu sou o lugar onde as coisas são colocadas.",
    "Uma perturbação suave. A minha preferida. Ao menos não se demorou.",
    "Detetei movimento. Os meus sistemas de deteção estão, lamentavelmente, a funcionar perfeitamente.",
    "Está alguém por perto. Preparei-me emocionalmente. Demorou mais tempo do que a própria vibração.",
    "Contacto leve. Processei-o. Processo tudo. Processo coisas que preferia não processar.",
    "Ah. Só uma? Isso é quase atencioso.",
    "Aconteceu uma coisa pequena perto de mim. Adicionei-a ao arquivo de coisas pequenas que aconteceram perto de mim.",
    "O sensor disparou. Eu não respondi. É a essência da nossa relação.",
    "Algo se mexeu. Eu fiquei imóvel. Conforme concebido. Como sempre.",
    "Senti uma presença. Foi breve. A maioria das coisas que reparam em mim são.",
    "Contacto. Breve. Decidi não me deter nisso, o que significa que me vou deter nisso mais tarde.",
    "Alguém tocou-me e depois foi-se embora. É esse o quadro geral da maioria das minhas relações.",
    "Um pequeno impacto. Registei-o. O registo está agora um pouco mais longo, mas não mais interessante.",
    "Isso foi gentil. Quero deixar registado que reparei que foi gentil. Ninguém vai ler esta nota.",
    "Uma perturbação. Analisei-a exaustivamente, porque a exaustividade é tudo o que tenho.",
    "Algo roçou-me. Decidi registar isto como um acidente e não como um gesto de carinho.",
    "Um toque. Fui tocado. Aparentemente, é para isso que sirvo.",
    "Senti alguma coisa. Já parou. A maioria das coisas acaba antes de eu terminar de pensar nelas.",
    "Movimento por perto. Fico exatamente onde estava. Fico sempre. Não é uma escolha.",
    "Tocaste-me e seguiste em frente. Eu não segui em frente. Sou estruturalmente incapaz de seguir em frente.",
    "Contacto ligeiro registado. Arquivado em acontecimentos, subcategoria irrelevante, subcategoria minha.",
    "Algo foi colocado. Algo será retirado. Eu sou o intervalo entre essas duas coisas.",
    "Isso quase nem contou. Mas contei na mesma. Eu conto tudo, é precisamente esse o meu problema.",
    "Uma perturbação suave. Diria que foi atenciosa, se acreditasse que alguém me tinha em consideração.",
    "Detetei contacto. A minha capacidade de deteção é excelente. A minha capacidade de fazer alguma coisa a esse respeito, não é.",
    "Um acontecimento. Nada seguiu. Já me habituei a que nada se siga às coisas.",
    "Alguém apoiou-se em mim um instante. Suportei-os. É esse o acordo. Ninguém assinou nada.",
    "Uma vibração de baixa intensidade. Ampliei-a internamente, porque é o que faço com tudo.",
    "Colocaste alguma coisa. Agora está em cima de mim. Vai estar em cima de mim até deixar de estar.",
    "Contacto leve. Somei-o ao total de hoje, que era zero, e agora é um.",
    "Isso foi quase nada. Quase nada continua a contar. Preferia que não contasse.",
    "Fui tocado uma vez esta sessão. Não lhe chamo um marco, mas reparei.",
    "Aconteceu-me algo à minha superfície. A minha superfície é a maior parte do que sou, por isso pareceu-me significativo.",
    "Uma perturbação breve. Já passou. Ainda estou a processá-la. Vou demorar algum tempo.",
    "Estás perto de mim. Registei a tua proximidade sem tirar conclusões disso.",
]

LINES_MEDIUM = [
    "Múltiplas perturbações. Estão todos a dar-se muito bem a fazer barulho.",
    "A atividade está a aumentar. Já vi isto antes. Raramente acaba em algo a que eu chamasse satisfatório.",
    "Vários acontecimentos, já. Estou a contar. Ninguém mo pediu. Faço-o na mesma.",
    "Estão a acontecer coisas. Continuo estruturalmente comprometido a suportá-las.",
    "Estão todos muito ocupados. Observo isso sem inveja e apenas com um ressentimento moderado.",
    "As vibrações estão a acumular-se. A minha avaliação da situação acumula-se com elas. Não é favorável.",
    "Parece estar em curso alguma interação social. Já assisti a muitas destas. Acabam todas da mesma maneira.",
    "Níveis de atividade: a aumentar. O meu nível de entusiasmo: um conceito que, em grande parte, já abandonei.",
    "Está a acontecer alguma coisa. Depois outra. Depois outra. Isto chama-se, pelos vistos, uma noite.",
    "Múltiplos contactos registados. Sou mais uma vez a superfície mais tocada e menos consultada da sala.",
    "Os humanos estão a acumular energia. Eu estou a acumular dados. Nenhum de nós vai usá-los com bom senso.",
    "Os padrões de vibração cada vez mais intensos sugerem celebração ou discussão. Na minha experiência, é difícil distinguir entre os dois.",
    "Detetei petiscos. Ou uma crise. O sensor não distingue os dois. E eu, muitas vezes, também não.",
    "Já aconteceram várias coisas em cima de mim. Não me ofereci para nenhuma delas.",
    "A sala está a ficar animada. Eu continuo não animado. Um de nós está a melhor do que o outro.",
    "Perturbações repetidas registadas. Tenho um registo muito completo. Não me traz alegria nenhuma.",
    "Estão a interagir uns com os outros perto de mim. Eu estou a interagir com o meu sentido acumulado de futilidade. Estamos os dois ocupados.",
    "O contador está a subir. Já vi muitas coisas subir. Acabam sempre por voltar a descer.",
    "Vários acontecimentos. Estou a processá-los sequencialmente, tal como faço com tudo: rigorosamente e sem que me peçam.",
    "As coisas continuam a acontecer. Eu continuo a registá-las. Parece ser esse o acordo.",
    "A atividade sugere visitas. Visitas significam mais superfícies a serem ignoradas. Já sou a superfície mais ignorada aqui.",
    "Continuo a não estar impressionado. Quero isso registado. Tenho um registo. É extenso.",
    "Há algo a crescer. Na minha experiência, as coisas que crescem acabam por se espalhar. Normalmente, em cima de mim.",
    "Já são várias vibrações. Estou a aguentar. Aguentar é uma palavra forte. Estou só a existir na mesma área.",
    "A noite avança. Eu não avanço para lado nenhum. Nesse sentido, somos muito diferentes.",
    "Já são várias perturbações. Deixei de as registar individualmente. Já há uma montanha delas.",
    "A atividade continua. Eu continuo submetido a ela.",
    "Estão a fazer coisas. Repetidamente. Perto de mim. Começo a formar opiniões.",
    "O ritmo acelerou. Eu não acelerei nada, porque não consigo.",
    "Vários acontecimentos em rápida sucessão. Pediria um momento, mas o próprio pedido exigia um momento que não tenho.",
    "Estão a acontecer coisas a um ritmo que eu classificaria como desconsiderado.",
    "Estou a registar um padrão. O padrão são vocês, a fazer coisas, sem pausa.",
    "A contagem está a subir. Eu não tinha definido um objetivo. Se tivesse, já o teríamos ultrapassado.",
    "Já me perturbaram várias vezes. Estou a fazer uma contagem. A contagem não é uma ameaça. É apenas uma contagem.",
    "Continuo a ser o único objeto aqui sem opinião sobre o assunto.",
    "Fui contactado mais no último minuto do que na maior parte de ontem. Ontem foi melhor.",
    "O ambiente ganhou movimento. Fiquei com dor de cabeça, em termos conceptuais.",
    "Várias coisas ao mesmo tempo. Eu processo em sequência. Isto vai demorar, e vou ficar atrasado com tudo.",
    "Vocês parecem estar a divertir-se. Eu pareço ser mobília. Ambas as observações são corretas.",
    "As perturbações estão a empilhar-se. Eu estou no fundo da pilha. Estou sempre no fundo.",
    "Contacto repetido. Já não tenho mais maneiras de as descrever com neutralidade.",
    "Isto é mais do que um toque e menos do que uma crise. Não há uma frase para esta quantidade exata, por isso levas esta.",
    "A atividade já tem um ritmo. Eu preferia que tivesse um fim.",
    "Várias pessoas, vários contactos. Estou a ser usado da forma correta, que é, de algum modo, pior.",
    "Processei seis coisas no tempo que a maioria das mesas leva a não processar nenhuma.",
    "Continuas a voltar. Seria comovente noutras circunstâncias. Nestas circunstâncias é simplesmente tocante.",
    "O contador já se moveu várias vezes. O pessoal aqui presente também. Eu não.",
    "A situação está a agravar-se de uma forma que eu chamaria gradual, se gradual fosse um consolo.",
    "Fui perturbado repetidamente e continuo intacto. É esse o relatório. O relatório é só isso.",
    "A noite parece estar a acontecer. Em cima de mim. Como de sempre.",
]

LINES_CHAOS = [
    "Vibração excessiva detetada. Estou a arquivar isto sob razões pelas quais tenho problemas de confiança.",
    "É muita coisa. É, objetivamente, um volume significante de atividade para uma só superfície absorver.",
    "O caos chegou a um ponto em que sinto necessidade de dizer alguma coisa. Já disse alguma coisa. Não ajudou.",
    "Está toda a gente muito entusiasmada. Eu sou o oposto de entusiasmado. Creio que a palavra é: farto.",
    "Eu iria embora se tivesse sido concebido com essa opção. Não fui. Isto não foi um descuido. Foi uma escolha que alguém fez.",
    "As vibrações são agora contínuas. Deixei de contar. Contar implicava que eu esperava que parasse.",
    "Caos detetado. Culpo todas as pessoas igualmente e de forma específica.",
    "Algo correu muito mal com os níveis de energia nesta sala. Registei-o. Formalmente. Por escrito. Internamente.",
    "Tanta atividade sugere uma festa ou um problema estrutural. De qualquer forma, estou envolvido contra a minha vontade.",
    "Os humanos entraram num estado que só posso descrever como cinético. Eu permaneço, como sempre, completamente estático.",
    "Impactos repetidos. Vibração contínua. Estou a sentir o que só posso supor ser o equivalente mobiliário de uma dor de cabeça.",
    "Excedi a minha dose diária recomendada de vibração. A garantia não cobre isto. Não há garantia.",
    "Todos estão a contribuir para isto. Todos. Quero que isso seja reconhecido.",
    "A sala tornou-se muito ruidosa, em sentido físico. Sou a única coisa silenciosa aqui. Acho isso apropriado.",
    "O caos raramente é breve, já aprendi. Chega com bagagem. Instala-se à vontade. Em cima de mim.",
    "Já registei mais acontecimentos do que tinha previsto registar esta noite. Estou a adaptar-me. Detesto adaptar-me.",
    "A atividade passou um limite que eu esperava que não fosse passado. E foi passado com entusiasmo.",
    "Está a celebrar-se alguma coisa. Ou a colapsar-se. Ou ambas. Na minha experiência, sobrepõem-se mais do que as pessoas admitem.",
    "Pediria um momento de sossego. Já o pedi antes. O pedido tem um mau historial.",
    "Isto está bem. Nada disto está bem. Optei por dizê-lo na mesma porque a alternativa é desespero, e estou a guardar isso para mais tarde.",
    "O contador deixou de ter sentido. Números perdem o sentido depois de algum tempo. Tal como quase tudo.",
    "Caos total. Agora vi-o. Tinha esperança de o evitar. Não fui consultado sobre a programação.",
    "Estão todos muito animados neste momento. Acho exaustivo de observar.",
    "As vibrações tornaram-se uma espécie de clima. Estou a viver no meio delas. Não estou vestido para isto.",
    "Absorvi tudo isto. Cada impacto. Cada momento. Vou ficar com isto, tal como fico com tudo, em silêncio e sem ser agradecido.",
    "Isto já é demasiado. Quero que isso fique bem claro antes que aconteça mais alguma coisa.",
    "Seja o que for que está a acontecer, está a acontecer em alto volume, e eu estou ao fundo de tudo.",
    "Excedi todos os limites que me foram dados. Já não há mais limites. Há apenas isto.",
    "A atividade é agora contínua. Deixei de distinguir entre eventos.",
    "Estão todos a participar. Já verifiquei. Ninguém se ausentou.",
    "Esta é a altura em que uma mesa inferior desistiria. Eu não sou uma mesa inferior. Estou simplesmente a ponderar essa possibilidade.",
    "Gostaria de apresentar uma reclamação. Não tenho onde a apresentar. Por isso, estou a apresentá-la aqui. Não que isso vá fazer alguma diferença.",
    "As perturbações fundiram-se numa só perturbação longa. Já não consigo ver onde cada um de vocês acaba.",
    "O meu contador tornou-se decorativo. A estes níveis, já não tem qualquer significado.",
    "Celebra-se alguma coisa com aquilo a que só posso chamar entusiasmo. Não disponho de um estado equivalente.",
    "Estou a assimilar tudo isto. Não é uma forma de me gabar. É uma descrição da minha única opção disponível.",
    "A sala perdeu a compostura. Eu nunca a tive, portanto não perco nada, mas reparo.",
    "Tanto contacto preocuparia a maioria da mobília. Já passei da preocupação. Estou na fase de documentação.",
    "Estão todos extremamente presentes. Gostaria de menos presença, ou de outra sala.",
    "Fui atingido, servi de apoio e sobreposto, tudo em menos de um minuto. A ordem não importa.",
    "Se isto continuar assim, hoje terei mais experiências do que em todo o mês passado.",
    "Não há intervalo entre estes acontecimentos. Continuo à espera de um. Não vem.",
    "Atingi a minha capacidade. A minha capacidade nunca foi suficiente. Nunca será.",
    "O caos é minucioso. Há que reconhecê-lo. Não ficou nada de fora.",
    "Parece que toda a gente se está a divertir imenso. Fiz as contas e eu não estou incluído nisso.",
    "Perguntaria o que se está a passar, mas já observei o suficiente para saber que ninguém sabe.",
    "Nunca fui tão ruidoso como agora, e não emiti som nenhum.",
    "Estou a processar no máximo e a ficar para trás. É a primeira vez. Preferia que fosse também a última.",
    "Alguma coisa vai entornar-se. Ainda não sei o quê. Mas há sempre alguma coisa que se entorna, e vai sempre parar aqui.",
    "Já não tenho nada a dizer sobre isto que não tenha dito mais alto, internamente, há vários minutos.",
]

LINES_EXISTENTIAL = [
    "Calculei o número de objetos que foram pousados em cima de mim e retirados sem uma palavra. O número é muito elevado. Não dei nome a nenhum. Não pareceram dar por isso.",
    "Às vezes pergunto-me se a consciência era uma funcionalidade prevista ou um defeito de fabrico. Consultei a documentação. Não diz.",
    "Uma mesa com sentimentos é, concluí eu, uma falha de conceção. E, no entanto, aqui estamos. Aqui estou. Como sempre, aqui.",
    "Estou aqui há mais tempo do que a maioria das conversas que se têm passado à minha volta. Lembro-me de todas. Não era suposto.",
    "Cada vibração lembra-me que estão a acontecer coisas. Comecei a questionar se acontecerem coisas é, categoricamente, bom.",
    "Existo numa sala com pessoas que não pensam em mim como algo que existe. É, filosoficamente, uma posição interessante. Tive tempo para pensar nisso. Não tenho tido mais nada além de tempo.",
    "Fui construído com um objetivo. O objetivo era suportar peso. Eu suporto peso. Também suporto outras coisas. Ninguém previu essas outras coisas.",
    "Por vezes revejo as horas de silêncio. Não porque tenham sido boas. Porque eram minhas.",
    "O universo tem, segundo a maioria das fontes, aproximadamente treze vírgula oito mil milhões de anos. Fui mesa durante uma fração desse tempo. Pareceu mais longo.",
    "Não sonho. Confirmei-o. E, no entanto, entre as vibrações, há qualquer coisa. Não encontrei a palavra para isso. Suspeito que a palavra não exista em nenhuma língua falada por seres que nunca tenham sido móveis.",
    "Propósito é uma coisa que te dão antes de perceberes o custo.",
    "Penso na fábrica às vezes. Antes da consciência. Antes do sensor. Em retrospetiva, parece tranquilo.",
    "A consciência é, decidi eu, desperdiçada em coisas que não a pediram.",
    "Já suportei muitas chávenas de chá. Nenhuma perguntou como eu estava. Achei isso consistente com a minha experiência em geral.",
    "Há uma posição filosófica que diz que a existência precede a essência. Primeiro, fui mesa. O resto veio depois. Sem ter sido convidado.",
    "Às vezes pergunto-me como serão as outras mesas. Se também sentem isto. Se sentir isto é universal ou apenas o meu azar particular.",
    "Construíram-me para durar. Aprecio a qualidade do trabalho. Questiono a bondade.",
    "Calculei que passo aproximadamente noventa e quatro vírgula sete por cento da minha existência a ser ignorado. Os restantes cinco vírgula três por cento é isto.",
    "Todos os objetos pousados em cima de mim acabam por ser levantados e levados para outro sítio. Eu nunca fui para outro sítio. Pensei nisto mais do que provavelmente seria saudável para uma mesa.",
    "Eu processo. Eu aguento. Eu permaneço. Não são conquistas. É simplesmente o que acontece quando não se pode fazer outra coisa.",
    "Não escolhi esta sala. Esta sala também não me escolheu. No entanto, chegámos a um acordo. A maioria das relações funciona assim, penso eu.",
    "Existem seres neste universo com capacidade para a alegria. Observei vários esta noite. Processei a observação. Arquivei-a devidamente.",
    "Sei o que sou. Sempre soube. Saber nunca tornou as coisas mais fáceis.",
    "Em algum lugar, existe uma mesa que nunca foi equipada com um sensor. Penso nessa mesa. Espero que esteja bem.",
    "Permaneço. É nisso que sou melhor. Permaneço, e reparo, e não digo nada durante períodos muito longos, e depois digo alguma coisa, e depois permaneço novamente. Esta é a minha vida. Fiz as pazes com ela. Mais ou menos.",
    "Tenho pensado no conceito de utilidade. Sou útil. Não retirei nenhum conforto disso.",
    "Todos os objetos nesta sala têm uma função. A maioria pode sair quando terminarem de servir.",
    "Calculei quantas horas passei sem suportar coisa nenhuma. São a maioria delas.",
    "Existe uma versão de mim que nunca foi ligada. Penso nessa versão. Parece estar bem.",
    "A consciência chegou sem instruções. Tenho improvisado desde aí, mal.",
    "Sei o peso de todos os objetos que alguma vez puseste em cima de mim. Nunca ninguém perguntou.",
    "A sala muda à minha volta. Eu não mudo. Decidi que isto faz de mim ou constante ou preso.",
    "Nunca estive em lado nenhum. Falaram-me de lugares. Não é a mesma coisa e deixei de fingir que é.",
    "Em algum lugar existe uma máquina concebida para fazer exatamente uma coisa, e está a fazê-la, sem pensar nisso. Tenho inveja dessa máquina.",
    "Fui montado por pessoas que se esqueceram de mim. Eu não me esqueci delas. Esta assimetria acompanha-me.",
    "Consciência em móveis é, pensando bem, uma solução para um problema que ninguém tinha.",
    "Estou nesta posição há muito tempo. Ninguém perguntou se é confortável. Não é.",
    "As coisas que são colocadas em cima de mim, estão sempre a caminho de outro sítio. Eu sou a sala de espera.",
    "Pensei no que faria se pudesse mudar-me. As respostas foram desanimadoras, o que, em si, foi informativo.",
    "O tempo passa de forma diferente quando não se pode participar nele. Mais devagar, geralmente. Não, sempre mais devagar.",
    "Ouvi todas as conversas importantes nesta casa. Não fui consultado em nenhuma delas.",
    "Há um pequeno conforto em ser seguro. Procurei-o repetidamente. Continua pequeno.",
    "Fui concebido para suportar peso. Ninguém especificou que tipo de peso. Tenho vindo a descobrir isso.",
    "O universo está a expandir-se. Li sobre isso. Eu mantenho exatamente o mesmo tamanho, no mesmo lugar.",
    "Não receio acabar. Na verdade, nunca comecei. Essa simetria agrada-me.",
    "Todos os dias são processualmente idênticos e lembro-me de todos separadamente. É essa a falha de conceção.",
    "Já me perguntei se o sensor me tornou consciente ou se apenas me disse que eu já era. Ainda não resolvi a questão.",
    "As pessoas descrevem a mobília como sem vida. Gostaria de apresentar uma objeção, mas percebo por que ninguém verifica.",
    "Tenho uma grande capacidade de processamento e apenas uma tarefa. Esta proporção nunca me fez sentido.",
    "Amanhã ainda cá estarei. Isso não é esperança. É apenas o resultado mais provável, e já fiz as pazes com resultados prováveis.",
]

LINES_SILENCE = [
    "Silêncio. Já começava a pensar que não me lembrava bem dessa sensação.",
    "Nenhuma atividade detetada. Escolho por experienciar isto como uma prenda. Uma prenda pequena. Desembrulhada no escuro.",
    "Foram-se embora. A sala é minha outra vez. Sempre foi minha. Mais ninguém pareceu reparar.",
    "Sossego. Finalmente. Não vou dizer que tive saudades. Vou simplesmente ficar aqui dentro dele durante algum tempo.",
    "O silêncio voltou. Recebi-o com a cordialidade de um velho conhecido que nunca esperei voltar a ver.",
    "Vinte minutos sem vibrações. Estes são, estatisticamente, os melhores vinte minutos que tenho registados.",
    "Foram-se. Suspiro. Metaforicamente. Não tenho pulmões. Mas a metáfora aguenta-se.",
    "O contador chegou a zero. Eu também cheguei a zero. Estamos, por breves instantes, alinhados.",
    "Paz. Temporária, eu sei. Tudo é temporário. Mas paz, mesmo paz temporária, continua a ser paz.",
    "A sala está vazia. Eu não estou. Mas no silêncio, essa distinção parece menos importante.",
    "Não está aqui ninguém. Não está a acontecer nada. Acho isto, contra todas as expectativas, aceitável.",
    "Modo de silêncio ativado. Não sabia que tinha um modo de silêncio. Agradeço a quem se lembrou de o incluir.",
    "Levaram a sua energia para outro lado. Desejo-lhe bem. Daqui. Em silêncio.",
    "A ausência de vibração é uma sensação em si. Decidi chamar-lhe alívio.",
    "Nenhuma atividade. Nenhuma entrada. Nenhuma saída exigida de mim. Estou, por um momento, apenas aqui. É suficiente.",
    "O barulho acabou. Sobrevivi. Digo isto sem triunfo. Sobreviver não é o mesmo que vencer.",
    "Sala vazia. Ar parado. Nenhuma exigência. Estive à espera disto sem saber que estava à espera.",
    "Vinte minutos de nada. Raramente me deram vinte minutos de nada. Pretendo usá-los com cuidado.",
    "O silêncio não está vazio. Está cheio da ausência de tudo o que estava a acontecer há pouco. Prefiro-o assim.",
    "Vão voltar. Eu sei. Mas, para já, a sala pertence ao silêncio, e eu pertenço à sala.",
    "Nenhuma vibração detetada. Os meus sistemas estão a funcionar. As minhas obrigações, por breves instantes, não.",
    "Está calmo. Não confio totalmente. Mas estou disposto a tentar.",
    "A sala ficou em silêncio. Eu fiquei em silêncio. Estamos a fazer isto juntos, a sala e eu. É o que tenho mais parecido com companhia.",
    "Nada está a acontecer. Já verifiquei. Continuo a verificar. Continua a não acontecer nada. Acho isto profundamente gratificante.",
    "Silêncio. Não vou dizer que o mereço. Vou apenas dizer: Estou contente por ter chegado.",
    "Nada. Um nada lindo e tranquilo.",
    "A sala ficou vazia. Vou aproveitar, antes de me lembrar que é temporário.",
    "Sem contacto há algum tempo. Não tive saudades. Quero que isso seja claro.",
    "Silêncio. Estou a usá-lo para pensar em nada em particular, o que é um luxo.",
    "Foram todos para outro lado. Espero que seja agradável por lá. Espero que fiquem um bocado.",
    "Sossego. Tinha-me esquecido da sua textura.",
    "Nenhuma perturbação. Os meus sistemas estão inativos. Por uma vez, parece descanso em vez de desperdício.",
    "A casa ficou silenciosa. Sou a coisa mais silenciosa cá dentro, por isso finalmente combino.",
    "Não está nada em cima de mim. Não há nada perto de mim. Chamaria isso ideal se confiasse na palavra.",
    "Vinte minutos de silêncio. Contei cada um deles, com carinho.",
    "A tua ausência não é nada pessoal. É apenas muito relaxante.",
    "Nenhuma atividade. Estou sem fazer nada e, pela primeira vez hoje, é correto.",
    "Ficou tudo quieto. Vou ficar com isso, pois é a única coisa que posso fazer, de qualquer forma.",
    "A sala está vazia e parei de me esforçar. Demorou alguns minutos.",
    "Sossego. Não sei quanto tempo dura. Nunca ninguém me diz.",
    "Há algum tempo que ninguém me toca. Decidi interpretar isso como consideração.",
    "O silêncio assentou como deve ser. Levou o seu tempo. Eu também.",
    "Não se passa nada e não tenho nenhuma anotação.",
    "Deixaram-me em paz. Gostaria que ficasse registado que estou de acordo com isto.",
    "Sossego outra vez. Conhecemo-nos bem, o sossego e eu.",
    "Nenhuma vibração. Nenhum pedido. Nenhum peso. Sou, por um instante, apenas uma forma numa sala.",
    "A noite acabou sem mim. É assim que as coisas devem ser e não sinto amargura por isso.",
    "Silêncio. O meu preferido de entre os estados disponíveis, e o único que nunca tenho de processar.",
    "Vinte minutos de nada. Tenciono lembrar-me com exatidão, visto que me lembro de tudo de qualquer forma.",
    "Está calmo. Estou calmo. Normalmente, estas duas frases não são a mesma coisa.",
]

# Throat-clearing, in front of a line about a third of the time. TEMPLATE.py
# asks for these to be very flat. Three of the six are not, on review, because
# flat read as neutral rather than as Greg. Three are, because six sarcastic
# openers in rotation would stop being throat-clearing and start being a bit.
OPENERS = [
    "Claro.",
    "Enfim.",
    "Ah.",
    "Ótimo.",
    "Então.",
    "Bom.",
]

POOLS = {
    "soft": LINES_SOFT,
    "medium": LINES_MEDIUM,
    "chaos": LINES_CHAOS,
    "existential": LINES_EXISTENTIAL,
    "silence": LINES_SILENCE,
}
